import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter_logs/flutter_logs.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:receive_intent/receive_intent.dart' as intents;
import 'package:stack_trace/stack_trace.dart';
import 'package:spaces/spaces.dart';
import 'package:wakelock/wakelock.dart';
import 'package:hibiki/media.dart';
import 'package:hibiki/models.dart';
import 'package:hibiki/pages.dart';
import 'package:hibiki/utils.dart';

Color? _savedSplashColor;

/// Application execution starts here.
void main() {
  /// Run and handle an error zone to customise the action performed upon
  /// an error or exception. This allows for error logging for debug purposes
  /// as well as communicating errors to Crashlytics if enabled.
  runZonedGuarded<Future<void>>(() async {
    /// Necessary to initialise Flutter when running native code before
    /// starting the application.
    final binding = WidgetsFlutterBinding.ensureInitialized();

    /// Ensure no pop-in for the app icon.
    binding.addPostFrameCallback((_) async {
      final context = binding.rootElement;
      if (context != null) {
        precacheImage(const AssetImage('assets/meta/icon.png'), context);
      }
    });

    /// Ensure the top and bottom bars are shown at launch and wake prevention
    /// is disabled if not reverted from entering a media source.
    Wakelock.disable();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

    // Match system bar overlays to the platform brightness immediately so the
    // status bar and navigation bar don't flash white on dark-mode devices.
    final platformBrightness =
        WidgetsBinding.instance.platformDispatcher.platformBrightness;
    SystemChrome.setSystemUIOverlayStyle(
      platformBrightness == Brightness.dark
          ? SystemUiOverlayStyle.light.copyWith(
              statusBarColor: Colors.transparent,
              systemNavigationBarColor: Colors.transparent,
              systemNavigationBarContrastEnforced: false,
            )
          : SystemUiOverlayStyle.dark.copyWith(
              statusBarColor: Colors.transparent,
              systemNavigationBarColor: Colors.transparent,
              systemNavigationBarContrastEnforced: false,
            ),
    );

    try {
      final raw = await const MethodChannel('app.hibiki.reader/splash')
          .invokeMethod<int>('getSplashColor');
      if (raw != null && raw != 0) _savedSplashColor = Color(raw);
    } catch (e) {
      debugPrint('[Hibiki] getSplashColor failed: $e');
    }

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);

    /// Some packages propagate their [StackTrace] in an unusual format as
    /// opposed to the format generated by Dart. This function allows the
    /// Flutter framework to handle such formats so they can be displayed
    /// appropriately.
    FlutterError.demangleStackTrace = (stack) {
      if (stack is Trace) {
        return stack.vmTrace;
      }
      if (stack is Chain) {
        return stack.toTrace().vmTrace;
      }
      return stack;
    };

    /// Create the provider container before running the app so the same
    /// [AppModel] instance is shared between the widget tree and the
    /// initialisation call below.
    final container = ProviderContainer();

    /// Start the application immediately so the user sees the loading page
    /// rather than a blank white screen while initialisation is in progress.
    runApp(
      UncontrolledProviderScope(
        container: container,
        child: const HoshiReaderApp(),
      ),
    );

    /// Initialise error log service.
    await ErrorLogService.instance.init();

    /// Initialise local file-based logging.
    await FlutterLogs.initLogs(
      logLevelsEnabled: [
        LogLevel.INFO,
        LogLevel.WARNING,
        LogLevel.ERROR,
        LogLevel.SEVERE
      ],
      timeStampFormat: TimeStampFormat.DATE_FORMAT_1,
      directoryStructure: DirectoryStructure.FOR_DATE,
      logTypesEnabled: ['device', 'network', 'errors'],
      logFileExtension: LogFileExtension.LOG,
    );

    /// Run the heavy initialisation after the first frame has been scheduled.
    /// [AppModel.isInitialised] will flip to true and notify listeners when
    /// done, causing [HoshiReaderApp] to navigate from [LoadingPage] to
    /// [HomePage].
    final appModel = container.read(appProvider);
    await appModel.initialise();

    // ── 预热：WebView 引擎 + ttu assets server ─────────────────────────
    // 两者互不依赖，各自 fire-and-forget。用户还在看主页/书架时就把冷启动
    // 成本吃掉：WebView 进程 ~500-1500ms，LocalAssetsServer ~200-800ms。
    unawaited(Future(() async {
      try {
        late final HeadlessInAppWebView warmup;
        warmup = HeadlessInAppWebView(
          initialUrlRequest: URLRequest(url: WebUri('about:blank')),
          onLoadStop: (controller, url) async {
            await Future.delayed(const Duration(milliseconds: 100));
            await warmup.dispose();
            debugPrint('[Hibiki] WebView engine pre-warmed');
          },
        );
        await warmup.run();
      } catch (e) {
        debugPrint('[Hibiki] WebView warmup failed (non-fatal): $e');
      }
    }));
    // ttuServerProvider 是非 autoDispose 的 FutureProvider.family，
    // read 触发后缓存在 container 里，用户点书时直接取 data 态。
    unawaited(Future(() {
      try {
        container.read(ttuServerProvider(appModel.targetLanguage));
        debugPrint('[Hibiki] ttu server provider triggered');
      } catch (e) {
        debugPrint('[Hibiki] ttu server warmup failed (non-fatal): $e');
      }
    }));

    /// Capture Flutter framework errors with full details.
    FlutterError.onError = (details) {
      // Suppress known Flutter framework bug: RawTooltipState creates
      // multiple tickers from SingleTickerProviderStateMixin.
      final msg = details.exceptionAsString();
      if (msg.contains('SingleTickerProviderStateMixin') &&
          msg.contains('RawTooltipState')) {
        return;
      }
      FlutterError.presentError(details);
      ErrorLogService.instance.log(
        'FlutterError: ${details.context?.toString() ?? 'unknown'}',
        msg,
        details.stack,
      );
    };
  }, (exception, stack) {
    /// Print error details to the console.
    final details = FlutterErrorDetails(exception: exception, stack: stack);

    /// Log the error.
    ErrorLogService.instance.log('UncaughtZone', exception, stack);
    FlutterLogs.logError(
      'hoshi_reader',
      details.exceptionAsString(),
      stack.toString(),
    );
  });
}

/// Encapsulates theming, spacing and other configurable options pertaining to
/// the entire app, with some parameters dependent on the [AppModel].
class HoshiReaderApp extends ConsumerStatefulWidget {
  /// Initialises an instance of the app.
  const HoshiReaderApp({super.key});

  @override
  ConsumerState<HoshiReaderApp> createState() => _HoshiReaderAppState();
}

class _HoshiReaderAppState extends ConsumerState<HoshiReaderApp>
    with WidgetsBindingObserver {
  final navigatorKey = GlobalKey<NavigatorState>();
  bool _isMainIntent = true;
  String? _pendingLookupText;

  late final StreamSubscription _intentsSubscription;

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      /// Receive all intents and parse them depending on which they are.
      intents.ReceiveIntent.getInitialIntent().then(
        (intent) => handleIntent(
          intent: intent,
          isInitial: true,
        ),
      );
      // Attach a listener to the stream for receiving intents.
      _intentsSubscription = intents.ReceiveIntent.receivedIntentStream.listen(
        (intent) => handleIntent(
          intent: intent,
          isInitial: false,
        ),
      );
    });
  }

  @override
  void dispose() {
    _intentsSubscription.cancel();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  void handleIntent({
    required intents.Intent? intent,
    required bool isInitial,
  }) async {
    if (intent == null) {
      return;
    }

    switch (intent.action) {
      case 'android.intent.action.MAIN':
        setState(() {
          _isMainIntent = true;
        });
        return;
      case 'android.intent.action.SEND':
        String? data = intent.extra!['android.intent.extra.TEXT'];
        if (data != null && data.trim().isNotEmpty) {
          textContextMenuAction(data);
        }
        break;
      case 'android.intent.action.PROCESS_TEXT':
        String data = intent.extra!['android.intent.extra.PROCESS_TEXT'];
        textContextMenuAction(data);
        return;
      case 'android.intent.action.WEB_SEARCH':
        String data = intent.extra!['query'];
        textContextMenuAction(data);
        return;
    }
  }

  void textContextMenuAction(String data) {
    if (data.trim().isEmpty) return;
    if (!appModel.isInitialised) {
      _pendingLookupText = data;
      return;
    }
    appModel.openRecursiveDictionarySearch(
      searchTerm: data,
      killOnPop: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    // Fields like locales/targetLanguage/theme are late and only available
    // after initialise() completes. Return a minimal app while loading.
    // LoadingPage calls Spacing.of(context) via buildLoading(), so we must
    // not use it here — render the spinner directly instead.
    //
    // Use system brightness to match the native splash and avoid a white
    // flash when the user has dark mode enabled.
    if (appModel.initError != null) {
      final brightness =
          WidgetsBinding.instance.platformDispatcher.platformBrightness;
      final isDark = brightness == Brightness.dark;
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: isDark ? ThemeData.dark() : null,
        home: Scaffold(
          backgroundColor: _savedSplashColor,
          body: Center(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(Icons.error_outline, size: 48, color: Colors.red),
                  const SizedBox(height: 16),
                  Text(
                    t.initialization_failed,
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: isDark ? Colors.white : Colors.black,
                    ),
                  ),
                  const SizedBox(height: 12),
                  SelectableText(
                    appModel.initError!,
                    style: TextStyle(
                      fontSize: 12,
                      color: isDark ? Colors.white70 : Colors.black87,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
          ),
        ),
      );
    }
    if (!appModel.isInitialised) {
      final brightness =
          WidgetsBinding.instance.platformDispatcher.platformBrightness;
      final isDark = brightness == Brightness.dark;
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: isDark ? ThemeData.dark() : null,
        home: Scaffold(
          backgroundColor: _savedSplashColor,
          body: Center(
            child: CircularProgressIndicator(
              color: isDark ? Colors.white70 : null,
            ),
          ),
        ),
      );
    }

    if (_pendingLookupText != null) {
      final text = _pendingLookupText!;
      _pendingLookupText = null;
      WidgetsBinding.instance.addPostFrameCallback((_) {
        textContextMenuAction(text);
      });
    }

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: appModel.navigatorKey,
      home: home,
      locale: locale,
      localizationsDelegates: const [
        HoshiReaderLocalizationsDelegate(),
      ],
      supportedLocales: appModel.locales.values,
      themeMode: themeMode,
      theme: appModel.theme,
      darkTheme: appModel.darkTheme,
      // This is responsible for the initialising the global spacing across
      // the entire project, making use of the [spaces] package.
      builder: (context, child) => Spacing(
        dataBuilder: (context) {
          return SpacingData.generate(10);
        },
        child: child!,
      ),
    );
  }

  /// Responsible for managing global app-wide state.
  AppModel get appModel => ref.watch(appProvider);

  /// The application will open to this page upon startup.
  Widget get home => _isMainIntent ? const HomePage() : const Scaffold();

  /// The current theme mode, which by default is based on system setting
  /// and toggleable.
  ThemeMode get themeMode =>
      appModel.isDarkMode ? ThemeMode.dark : ThemeMode.light;

  /// The current locale, dependent on the active target language.
  Locale get locale => appModel.targetLanguage.locale;
}

/// Used to override certain strings.
class HoshiReaderLocalizations extends DefaultMaterialLocalizations {
  @override
  String get licensesPageTitle => t.options_attribution;
}

/// Delegate for [HoshiReaderLocalizations].
class HoshiReaderLocalizationsDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  /// Initialise this delegate.
  const HoshiReaderLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<HoshiReaderLocalizations> load(Locale locale) {
    return SynchronousFuture<HoshiReaderLocalizations>(
        HoshiReaderLocalizations());
  }

  @override
  bool shouldReload(HoshiReaderLocalizationsDelegate old) => false;
}
