name: hibiki_dictionary
description: Dictionary engine, FFI bindings, and language implementations for Hibiki
publish_to: none


environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.41.6"

dependencies:
  flutter:
    sdk: flutter
  hibiki_core:
    path: ../hibiki_core
  ffi: ^2.1.3
  collection: any
  kana_kit: ^2.0.0
  ruby_text:
    git:
      url: https://github.com/arianneorpilla/RubyText
      ref: cb723f87c9ac575aa735b40016c0ffb3242d921e
  dart_mappable: ^4.0.0-dev.1
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.2
  archive: ^3.6.1
  async_zip: ^0.1.0
  file_picker: ^8.0.0
  path: ^1.8.2
  recase: ^4.1.0
  flutter_archive: ^5.0.0
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_mappable_builder: ^4.0.0-dev.2
  build_runner: ^2.3.3
